# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc4605c1ce8178f1dc4bca8720f2d1076bfcaf67f81026aa9500f5b710c21b1ca7df172d24e15deb5618650c2d4e6fc0685a6f080b8f8758336ec4e8cf10024a

test:
  secret_key_base: 312cf37f248288d42c74b2ca3a658af16cff35f5e729957caa80ede7c590205a398582e5f5d71ee6afef1bba4c3293446d975c43a3c17b18ca7990bc5aa1ceac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
